version: '3'

services: 
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports: 
            - "2181:2181"
    kafka-10:
        image: wurstmeister/kafka
        container_name: kafka-10
        ports: 
            - "9092:9092"
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    kafka-11:
        image: wurstmeister/kafka
        container_name: kafka-11
        ports: 
            - "9093:9092"
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    